[package]
name = "stalkermap-cli"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
stalkermap = { path = "../stalkermap", features = ["std", "tokio-dep", "agnostic"] }
tokio = "1.47.1"
