[package]
name = "stalkermap-cli"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
tokio = { version = "1.47.1", features = ["full"]}
stalkermap = { path = "../stalkermap", features = ["tokio-dep"]}
